---
- name: Install dependencies for PostgreSQL 
  apt: name={{ item }} update_cache=true state=latest
  with_items:
  - bash
  - openssl
  - libssl-dev
  - libssl-doc

  - name: Install PostgreSQL 
    apt: name={{ item }} update_cache=true state=present
    with_items:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python3-psycopg2

  - name: Ensure the PostgreSQL service is running
    service: name=postgresql state=started enabled=y

  - name: Create the database specified in group_var
    become: true
    become_user: postgres
    postgresql_db: name={{ mysql_app_db }}
         template='template0'
         state=present

  - name: Ensure user has access to the new database
    become: true
    become_user: postgres
    postgresql_user: db={{ mysql_app_db }}
         name={{ mysql_app_user }}
         password={{ mysql_app_pass }}
         priv="{{ mysql_app_db }}.*:ALL"
         state=present
         
  - name: Ensure user does not have unnecessary permissions
    become: true
    become_user: postgres
    postgresql_user: name={{ db_user }}
         role_attr_flags=NOSUPERUSER,NOCREATEDB
         state=preset