---
- name: Restart PHP-FPM
  service:
    name: php7.2-fpm
    state: restarted
    
# - name: Restart apache2
#   service:
#     name: apache2
#     state: restarted
- name: restart nginx
  service: name=nginx state=restarted